### PR TITLE
Prepare to move the module in java/io.foojay.disco

### PR DESCRIPTION
**Pull request by emilianbold**

### CODE REVIEW

**Comment by geertjanw** [comment]
Won't the Azul license headers be a problem?

**Comment by emilianbold** [comment]
@geertjanw yes, I mentioned this in #42. In practice I think we will also need a NOTICE file for it (and whatever entries NetBeans codebases uses to generate this list).

But, ideally, we could just have both under Apache license (I don't think it's a big problem, Azul could relicense it under multiple licenses...)

**Comment by geertjanw** [comment]
So better would be for Azul to remove the Azul license headers?

**Comment by emilianbold** [comment]
Yes, ideally remove them, and dual-license disco client under Apache 2.0 and whatever BSD license you had before.

Having everything under a single license should also simplify donation to ASF.

**Comment by geertjanw** [comment]
It will remain having Azul license headers and be BSD licensed. That should be fine, right?

**Comment by emilianbold** [comment]
I can do it either way but honestly discoclient *not* being in Maven Central plus being under a non-Apache license complicates things needlessly. I did wonder if it wouldn't be quicker to just use the REST API myself and avoid discoclient entirely.

I will revert the inclusion, etc. and update this PR.

**Comment by emilianbold** [comment]
@geertjanw please review the latest changes. I'm including the JAR again.

This brings us pretty close to making a PR against the NetBeans main repo. I just need to:

* add the module to the cluster list (in the other PR)
* remove the extra files from release/ and from nbproject/
* ask folks to upload discoclient JAR to OSUOSL (since it's not on Maven Central).

**Pull request merged**
